services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - RUST_BACKTRACE=1
      - CARGO_TARGET_DIR=/tmp/target
      - CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
    depends_on:
      - postgresql
    tty: true
    volumes:
      - ../apps/services:/app
      - pg_rust_samples_cargo_cache:/usr/local/cargo/registry
      - pg_rust_samples_target_cache:/tmp/target
    working_dir: /app
    security_opt:
      - seccomp:unconfined

  postgresql:
    image: postgres:17.0
    environment:
      - POSTGRES_DB=web
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - pg_rust_samples_postgresql_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.0.1
    ports:
      - 6379:6379
    volumes:
      - pg_rust_samples_valkey_data:/data

volumes:
  pg_rust_samples_cargo_cache:
  pg_rust_samples_target_cache:
  pg_rust_samples_postgresql_data:
  pg_rust_samples_valkey_data: