[package]
name = "sample_sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
common = { path = "../crates/common" }
env_logger = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
