[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }